<!DOCTYPE html>
<html lang="cs-cz">
        <head>
                <base href="/localhost" />
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <!-- Latest compiled and minified CSS -->
                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

                <!-- jQuery library -->
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

                <!-- Latest compiled JavaScript -->
                <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
                <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
                <title><?= $titulek ?></title>
                <meta name="description" content="<?= $popis ?>" />
                <meta name="keywords" content="<?= $klicova_slova ?>" />
                <link rel="stylesheet" href="style.css" type="text/css"/>
        </head>

        <body>

                <?php require 'pohledy/navbar.php'; ?>

                <br clear="both" />

                <div>
                        <?php $this->kontroler->vypisPohled();?>
                </div>

        </body>
</html>